### PR TITLE
Ensure line-break is not OS dependent.

### PR DESCRIPTION
**Pull request by lucasmichot**
Ensure line-break is not OS dependent.

### CODE REVIEW

**Comment by franzliedke** [comment]
Can you explain the use-case (or the bug this prevents)? As far as I remember, this adapter is only used in unit testing...

**Comment by lucasmichot** [comment]
It is, but tests are also run in Windows OS

**Comment by franzliedke** [comment]
Are you saying tests are not passing on Windows?

**Comment by lucasmichot** [comment]
I am personally not using Windows for my development, but this has come an issue in other situations. I am curious to see if they pass on Widows tho

**Comment by franzliedke** [comment]
From a quick check, we only used `assertContains`, never compared the full string.

**Comment by aidantwoods** [comment]
Although this adapter is only used for testing, it seems to me that the most correct thing to do would be to use "\r\n" in all cases so that we're following the standard HTTP/1.1 message format?

https://tools.ietf.org/html/rfc7230#section-3

**Comment by aidantwoods** [comment]
We never resolved this one, right? Any objections to switching from `\n` to `\r\n` for the string adapter? (we can write some logic into the tests to auto-convert what we've typed – since all files are using unix LF EOLs).

(this would have the benefit of being *technically* valid for output in a HTTP response – though I would be surprised if anything actually rejected headers because of LF instead of CRLF).

**Pull request closed without merging**
