### PR TITLE
Switch code and tests to PSR-4

### PR DESCRIPTION
**Pull request by lucasmichot**
Switch code and tests to PSR-4

Also:
- Add `.gitattributes`
- Update `.travis.yml`

### CODE REVIEW

**Comment by franzliedke** [comment]
I like this!

What about `aidan` or something similar as namespace?

@aidantwoods Since you have already released a 1.0 version, how about creating a new branch that breaking PRs like this one can be sent to? I would like to send one for the framework adapters as well. :)

**Comment by lucasmichot** [comment]
Hey Franz, wie geht's? ;-)

Maybe `Aidan\` or `Aidantwoods\` ? Let me know @aidantwoods 
Totally up for a new branch too !

**Comment by aidantwoods** [comment]
Looks great! 😄 

Maybe go for `aidantwoods\SecureHeaders` for the namespace? (Might as well make it copy-pastable from the packagist name/github URL)

New branch sounds good too! If I create a 2.x branch, then we can collate a few of these changes into the next major release without changing the major version every couple days 😜

**Comment by lucasmichot** [comment]
@aidantwoods I've just updated the namespace with https://github.com/aidantwoods/SecureHeaders/pull/8/commits/e5bffd7f5cf1d604174b3f3332b5edbd427ee7e9 : `Aidantwoods\SecureHeaders`
Can find the `2.0` branch, can you create it so I can retarget this PR to this new branch?

**Comment by ameliaikeda** [comment]
@aidantwoods Maybe keep the vendor name in the same format as PSR-2? e.g. `AidanWoods`, or capitalize the `A` at the start at the very least?

**Comment by aidantwoods** [comment]
Okay, yeah that's a good point @ameliaikeda – shall we just go with `AidanWoods` then?

@lucasmichot there's a `2.0` branch there now :)

**Comment by franzliedke** [comment]
:+1: PR looks good.

Once @lucasmichot has changed the namespace. (And hi back. It's funny how small the PHP world is.)

**Comment by lucasmichot** [comment]
And Berlin is even smaller :-)

@aidantwoods the namespace has been changed to `Aidantwoods\SecureHeaders` and this PR now targets branch `2.0`

**Pull request merged**
