### PR TITLE
Custom style guide and contributing

### PR DESCRIPTION
**Pull request by aidantwoods**
- [x] Add custom styling
- [x] Add contributing guide explaining style checker, style convention, (any other useful info)

### CODE REVIEW

**Comment by aidantwoods** [comment]
@lucasmichot, @franzliedke any ideas on why this is failing in this repo, but not over in https://github.com/Parsemd/Parsemd ?

screen shot 2017-06-16 at 17 35 39

**Comment by lucasmichot** [comment]
Have you tried to set a token : https://getcomposer.org/doc/articles/troubleshooting.md#api-rate-limit-and-oauth-tokens ?

**Comment by aidantwoods** [comment]
I may have to do that, weird I didn't need to on my other repo though?

**Comment by aidantwoods** [comment]
Right, that seems to have fixed it – guess I must've lucked out in my other repo on the initial build and the composer installation is just going from cache from then on 🤷‍♂️

**Pull request merged**
