### PR TITLE
2.0 another cleanup

### PR DESCRIPTION
**Pull request by franzliedke**
This makes `apply()` the public API instead of `done()` and adjusts all the tests.

Also, I removed a bunch of now-obsolete methods and properties. (PhpStorm also marked them as unused.)

IMO, `done()` should now be removed, but that requires a decision about the `doneOnOutput()` stuff.

### CODE REVIEW

**Comment by aidantwoods** [comment]
> IMO, done() should now be removed, but that requires a decision about the doneOnOutput() stuff

`applyOnOutput(HttpAdapter $http = null)` ?

**Comment by franzliedke** [comment]
Honestly, I would leave out that functionality - this is the kind of thing that the consumer of the library has to take care of. Again, this affects the global state, and it's not how modern PHP frameworks handle the request lifecycle.

Maybe it can be integrated into the proposed `Response` / `Result` class?

**Comment by aidantwoods** [comment]
Still, for those who don't use frameworks it's a nice feature to have (puts SecureHeaders into a mode more similar to PHPs native `header` – where configured headers will be sent on output). For those who use frameworks, they can simply not use the feature 😉

**Comment by aidantwoods** [comment]
I've added it in for now, can refactor if it ends up being better implemented in the `Response` / `Result` you mentioned though

**Pull request merged**
