### PR TITLE
Formally commit to Semantic Versioning 2

### PR DESCRIPTION
**Pull request by aidantwoods**
Put it in writing that SecureHeaders will commit to semver, and declare a public API.

### CODE REVIEW

**Comment by aidantwoods** [comment]
Once again, I'll leave this open for seven days (until 9th July) for any objections/suggestions/comments... to be made, or longer if any are outstanding by that time.

**Comment by aidantwoods** [comment]
Issue:
Would like strict mode to adopt new headers without a major version bump. New headers have the potential to cause BC breaks if we consider headers emitted part of the public API (since new headers will impose more restrictions on the page served – potentially breaking things).

Maybe this isn't feasible and major version will just need a bump for new headers, or we could have some kind of work around. Would be good to discuss this a little.

**Comment by franzliedke** [comment]
You might want to check out the `@public` and/or `@private` tags for PHP doc blocks. They might help specify what exactly is public API, without having to keep the list in README.md in sync.

As for your example: I would consider that a breaking change. It would be a clear change in (hopefully documented) behavior, with the potential for breaking things on certain server setups.

**Comment by aidantwoods** [comment]
> You might want to check out the `@public` and/or `@private` tags for PHP doc blocks. They might help specify what exactly is public API, without having to keep the list in README.md in sync.

Ah that sounds like something worth doing! Got a link to docs for those, I can only find [`@access`](https://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_tags.access.pkg.html) (but not in the phpdocumentor2 docs), and [`@api`](https://phpdoc.org/docs/latest/references/phpdoc/tags/api.html). Possibly `@api` is the better one of these that I can find?

> As for your example: I would consider that a breaking change. It would be a clear change in (hopefully documented) behavior, with the potential for breaking things on certain server setups.

Yes, after having a think for a bit – I think the best approach is to have a version bump (doesn't feel right excluding a specific function from semver, or something like that). New security headers don't come around hugely often, but when they do if we include them by default in strict mode then a version bump is really the responsible thing to do (as much as I'd love to get everyone auto-updating to better settings – it'll probably break things, so can't do it).

And RE the
>  It would be a clear change in (hopefully documented) behavior

Hopefully adding a changelog (https://github.com/aidantwoods/SecureHeaders/pull/42) as part of the dev process should help keep track of breaking changes.

**Pull request merged**
