### PR TITLE
Ensure the codebase respects PSR-2.

### PR DESCRIPTION
**Pull request by lucasmichot**
Ensure the codebase respects PSR-2.

### CODE REVIEW

**Comment by aidantwoods** [comment]
Definitely agree on the trailing whitespace trimming + adding new line to the end of a file, a couple instances where braces haven't been placed on the next line, and some missing explicit visibility declarations.

Most of the changes are to brace placement though.

While I generally like most the of PSR-2 recommendations, I don't like their (seemly arbitrary to me) decision to recommend that class/method braces should look like this:

```php
class Foo
{
    public function bar()
    {
        ...
    }
}
```

but control structure braces should look like this:

```php
foreach ($foo as $bar) {
    if ($bar === 'boo') {
        ...
    }
}
```

Personally I prefer the former style because it separates each structure into distinct (more readable) blocks. What I really don't want is having (again, apparently arbitrary) inconsistencies in style for different code structures.

That and I tend to like to leave whitespace either side of the logical negation operator so it's not so easy to skim over 🤷‍♂️

**Comment by franzliedke** [comment]
I am pretty sure you can enforce your custom style guide with a tool like [PHPCodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer). It has presets for PSR-2, but can be adapted to more custom rools like these ones as well. And finally, you can use Travis-CI to check these issues as well.

**Comment by aidantwoods** [comment]
I like this!
Any idea if there are any nice presets that I can switch on when defining the custom ruleset? Otherwise I'll take a more in depth look at the custom rules tomorrow.

**Comment by franzliedke** [comment]
I am afraid I don't know. But it should just be a matter of enabling a few flags (in a special file that PHPCS reads, I believe). 

If that is too complicated, you can also try out StyleCI. It allows the configuration through a GUI, but might not be as flexible. 

Good night...

**Comment by aidantwoods** [comment]
No worries. Yeah I had a cursory look at the docs, looks like the flags all go something like this `"Squiz.Strings.DoubleQuoteUsage.ContainsVar"`. So it appears I may have to hunt down the right options. There also appears to be a way to do it by specifying custom PHP scripts to do parts of the validation, which may not be too difficult if it comes down to it (since these are very minor specific changes). But I'll leave that till tomorrow.

I think I'd prefer this over StyleCI if I can get it working, (the only way to get my current styling to pass in StyleCI appeared to be turning off brace checks all together – which would make it considerably less useful).

> Good night...

Night!

**Comment by aidantwoods** [comment]
@franzliedke 
Okay, so as promised I did take a look at phpcs. Unfortunately while a lot of the options they've added as configurable are pretty easy to turn on/off – it looks like I won't be able to (even make minor changes) to the stuff I want without `grep`ing for the error messages I'm seeing and making many minor code changes.

(Unfortunately the existing code isn't that extensible, so changing small bits of functionality means re-implementing entire methods). I've also had issues where validation rules that aren't listed by `phpcs -e` are still being applied (meaning rules are using each other without being configurable within the ruleset files :/).

I still think this is a good tool to use (since most of the code I want to use has been written), but it'll require a bit more work to get right than I had hoped.

**Comment by franzliedke** [comment]
Hmm, at this point I would humbly suggest configuring this as far as you can get with PHPCS, and then just rolling with it. IMO, an enforcable style guide is more important than personal preferences, but ultimately that's your decision, of course. ;)

**Comment by lucasmichot** [comment]
Fixed conflicts

**Comment by lucasmichot** [comment]
What about this PR @aidantwoods ?

**Comment by lucasmichot** [comment]
I could not see the build status of StyleCI either @aidantwoods

**Comment by lucasmichot** [comment]
Conflict resolved @aidantwoods

**Comment by aidantwoods** [comment]
Alright, so I've given it some thought and I think making it easier for others to contribute is probably more important than my personal preferences RE the code styling.

If at some point in the future I can find something that'll enforce *my* style guide then I'll probably switch back, but for now I'll go with what's available :)

**Comment by aidantwoods** [comment]
So I'm looking into StyleCI again – it appears the only way to isolate which repos it has write access to would be to:

1. Make use of GitHub's ToS allowance for an additional free bot account by creating one to use exclusively to facilitate StyleCI access.
2. Transfer the SecureHeaders repo to an organisation
3. Give this new account admin access to the repo from within the organisation
4. Configure StyleCI from this new account

**Comment by lucasmichot** [comment]
Ping @GrahamCampbell

**Comment by aidantwoods** [comment]
From StyleCI's end, I can't see why they'd need any more permissions than TravisCI:
screen shot 2017-04-10 at 13 46 32

In contrast this is what StyleCI requests:
screen shot 2017-04-10 at 13 46 57

As far as that goes, even the GitHub [help page](https://help.github.com/articles/connecting-with-third-party-applications/#repositories) cautions that level of access:
screen shot 2017-04-10 at 13 47 41

**Comment by GrahamCampbell** [comment]
StyleCI has to do this so that it can add it's webhook and deploy key. Travis does not need this, since it has special integration with GitHub.

**Comment by GrahamCampbell** [comment]
We have no plans to change the access level we need, since it's perfectly reasonable.

**Comment by franzliedke** [comment]
Any chance to make these permissions optional and create webhook and deploy key manually?

**Comment by GrahamCampbell** [comment]
Sorry, there are no plans to add this.

**Comment by GrahamCampbell** [comment]
For security reasons, we can't reveal our webhook secret key.

**Comment by aidantwoods** [comment]
Based on that response I don't think I can allow StyleCI persistent access to my repos. If they are compromised at any point, I'd rather my repos didn't go with them. And I don't really like the sound of a global secret being used here :/

**Comment by GrahamCampbell** [comment]
> And I don't really like the sound of a global secret being used here :/

It's actually not a global secret. It's generated on a per repo basis, however, we're still not giving it out to users.

**Comment by GrahamCampbell** [comment]
We have asked GitHub to implement more fine grained permissions, however they haven't yet.

Also, actually, to get the most out of StyleCI, we need push access to the code, you can make use of our one-click fix system, designed to save people time. Most people want things to just work, with no effort on their part.

**Comment by franzliedke** [comment]
@aidantwoods I guess you either need to live with it, or use an alternative like PhpCodeSniffer on Travis. Not as comfortable, though.

**Comment by aidantwoods** [comment]
I've had another look at phpcs, but it seems that's it isn't happy with the current code (despite StyleCI giving it the OK), so it might require a few bug fixes before I can use it.

Unfortunately I'll never just be comfortable giving admin access to all my repos when I only the only functionality I actually want could be satisfied by read. It's an huge unnecessary risk, but I'd love to give StyleCI a go if they ever implement a mode that doesn't require giving them admin access to all my repos for the entire duration of use. 

@GrahamCampbell can StyleCI not just request access to webhooks if you really can't let users access these keys? Webhooks are a very different level of access to that given by admin on the whole repo.

**Comment by GrahamCampbell** [comment]
> Unfortunately I'll never just be comfortable giving admin access to all my repos when I only the only functionality I actually want could be satisfied by read.

Well unfortunately that means you can't use StyleCI. Sorry.

> I've had another look at phpcs, but it seems that's it isn't happy with the current code (despite StyleCI giving it the OK), so it might require a few big fixes before I can use it.

I'd recommend PHP-CS-Fixer over phpcs. :)

**Pull request merged**
