### PR TITLE
Apply fixes from StyleCI

### PR DESCRIPTION
**Pull request by aidantwoods**
This pull request applies code style fixes from an analysis carried out by [StyleCI](https://styleci.io).

---

For more information, click [here](https://styleci.io/analyses/X0y2G4).

### CODE REVIEW

**Comment by aidantwoods** [comment]
@lucasmichot are there any nice keywords for the config to stop StyleCI faulting the opening brace of `if` and `foreach` being on a new line? I know its not PSR-2 (not sure why – function and class braces are forced on a new line).

Takes a lot away from readability to put it on the same line IMO.

**Comment by lucasmichot** [comment]
I am sure there are / ping @GrahamCampbell

**Comment by aidantwoods** [comment]
Also for the whitespace trim before the not operator here
screen shot 2017-01-10 at 19 58 43

Again, much more readably IMO if the operator stands out more at the beginning of an `if`

**Comment by aidantwoods** [comment]
Thanks :D

**Comment by aidantwoods** [comment]
Not sure about StyleCI acting on its own to delete that branch there

**Comment by lucasmichot** [comment]
This apply to `master` so this can be merged.

**Comment by lucasmichot** [comment]
Not sure StyleCI delete the analysis branch automatically

**Comment by aidantwoods** [comment]
Hmm... I've disabled StyleCI for the moment – the checks won't be that useful until I can find those config options 😜 

Also, not sure about it deleting that branch without prompting o.0 know of any style checkers that don't require write permission to the repo?

**Comment by lucasmichot** [comment]
Sure ! You can let this PR open for now
It will be updated with after any commit on the master branch, including parameters change in the styleci config file :-)

Neverming about deleting the `analyis-` branches, you can remove them from time to time...

**Comment by svenluijten** [comment]
Doesn't look like the check you're looking for exists at the moment. https://styleci.readme.io/docs/fixers

**Comment by svenluijten** [comment]
Actually, it's likely the `braces` check doing it: https://styleci.readme.io/docs/fixers#braces.

**Pull request closed without merging**
